name: Build and Deploy GH Pages

on:
  push:
    branches: main

jobs:
  deploy_gh_pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm ci
      - run: npm run predeploy
      - run: npm run deploy

